experiment:
  # semantic or libet
  selected: libet
  details:    
    semantic:
      name: semantic categorisation
      participants: ['A', 'B', 'C', 'D']
      triggers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    libet:
      name: libet experiment
      # note participants 1 & 3 don't exist
      participants: [2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
      triggers: ['L', 'R']

model_parameters:
  percentage_training_&_validation_to_testing_split: 80
  kfolds: 5
  # Number of epochs per training fold.
  epochs: 20
  # 0: "All" (all participants' data combined), 1: "Single" (each participant's data seperate)
  comparison: 1

os:
  mac_m1:
    io_paths:
      set_files: 
      csv_files: /Users/james.wolfaardt/code/__ben/Code/Siobhan_Data
      pickle_files: /Users/james.wolfaardt/code/__ben/Code/Deep_Learning-EEG_Data/outputs/pickles
      model_files: /Users/james.wolfaardt/code/__ben/Code/Deep_Learning-EEG_Data/outputs/models
      confusion_matrices: /Users/james.wolfaardt/code/__ben/Code/Deep_Learning-EEG_Data/outputs/cms
  ubuntu: 
    io_paths:
      set_files: 
      csv_files: 
      pickle_files: 
      model_files: 
      confusion_matrices: 
  windows:
    io_paths:
      set_files: E:\\Skripsie\\Data\\New\\1-Pre_Processed 
      csv_files: E:\\Skripsie\\Data\\New\\2-CSV 
      pickle_files: 
      model_files: 
      confusion_matrices: 
